
import './globals.css'
import { Inter } from 'next/font/google'
//import {CartProvider} from '@component/contexts/cartContext'
import NavBar from '@component/components/nav/navbar'
import Footero from '@component/components/footer/footero'
import Providers from '@component/store/provider'
import BottomWP from '@component/components/whatsapp/bottomWP'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

console.log(inter)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:wght@300;400&display=swap" rel="stylesheet"/>
      </head>
      <Providers>
        <body className={inter.className}>
          <NavBar/>
          <BottomWP/>
          {children}
          <Footero/>
          </body>
      </Providers>

    </html>
  )
}
